# Generated by Django 3.2.7 on 2021-09-01 13:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100)),
                ('card_desc', ckeditor.fields.RichTextField()),
                ('card_assigned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Maintainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')])),
                ('admin', models.BooleanField(default=False)),
                ('disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_desc', ckeditor.fields.RichTextField()),
                ('project_maintained_by', models.ManyToManyField(to='TracKer.Maintainers')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=100)),
                ('list_mapped_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TracKer.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_desc', ckeditor.fields.RichTextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_mapped_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TracKer.cards')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TracKer.maintainers')),
            ],
        ),
        migrations.AddField(
            model_name='cards',
            name='card_assigned_to',
            field=models.ManyToManyField(to='TracKer.Maintainers'),
        ),
        migrations.AddField(
            model_name='cards',
            name='card_mapped_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TracKer.list'),
        ),
    ]
