# Generated by Django 3.2.7 on 2021-09-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TracKer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
        migrations.RenameModel(
            old_name='Maintainers',
            new_name='Maintainer',
        ),
    ]
