# Generated by Django 3.2.7 on 2021-09-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TracKer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainner',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='maintainner',
            name='password',
            field=models.CharField(default='pass', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
