# Generated by Django 3.2.7 on 2021-09-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TracKer', '0002_auto_20210901_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_assigned',
            new_name='is_card_assigned',
        ),
    ]
