# Generated by Django 3.2.7 on 2021-09-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TracKer', '0003_auto_20210908_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='maintainer',
            name='password',
            field=models.CharField(default='apple', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
