# Generated by Django 3.2.7 on 2021-09-06 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TracKer', '0003_rename_card_assigned_card_is_card_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_mapped_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_to_project', to='TracKer.project'),
        ),
    ]
