# Generated by Django 3.2.7 on 2021-09-08 04:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TracKer', '0004_auto_20210908_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100)),
                ('card_desc', ckeditor.fields.RichTextField()),
                ('is_card_assigned', models.BooleanField(default=False)),
                ('card_assigned_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_desc', ckeditor.fields.RichTextField()),
                ('project_maintained_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=100)),
                ('list_mapped_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists_in_project', to='TracKer.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_desc', ckeditor.fields.RichTextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('comment_mapped_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_in_card', to='TracKer.card')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_mapped_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_in_list', to='TracKer.list'),
        ),
    ]
