# Generated by Django 3.2.7 on 2021-09-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TracKer', '0004_alter_list_list_mapped_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_mapped_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_in_list', to='TracKer.list'),
        ),
        migrations.AlterField(
            model_name='list',
            name='list_mapped_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists_in_project', to='TracKer.project'),
        ),
    ]
