# Generated by Django 3.2.7 on 2021-09-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TracKer', '0005_auto_20210908_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainer',
            name='enrollment_number',
            field=models.IntegerField(default=20114000),
        ),
    ]
