# Generated by Django 3.2.7 on 2021-09-10 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TracKer', '0006_maintainer_enrollment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_card_assigned',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_assigned_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
